on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.8.3
          vessel-version: 0.6.2
      - run: for i in test/*.mo ; do $(vessel bin)/moc $(vessel sources 2>/dev/null) --package stable src -r $i ; done
